on:
 schedule:
   - cron: 0 0 * * 0
 workflow_dispatch:

name: Trigger Build
jobs:
 release:
   name: Create timestamp file
   runs-on: ubuntu-latest
   steps:
     - name: Create timestamp file
       uses: technote-space/create-pr-action@v2
       with:
         EXECUTE_COMMANDS: |
           date +%s > last_autobuild.txt
         COMMIT_MESSAGE: 'Committing timestamp PR to trigger build'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'devops@dwolla.com'
         PR_BRANCH_NAME: 'main'
         PR_TITLE: 'Commit timestamp PR to trigger build'
